# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='array.proto',
  package='test2',
  serialized_pb=_b('\n\x0b\x61rray.proto\x12\x05test2\"<\n\nQuaternion\x12\n\n\x02n1\x18\x01 \x01(\x02\x12\n\n\x02n2\x18\x02 \x01(\x02\x12\n\n\x02n3\x18\x03 \x01(\x02\x12\n\n\x02n4\x18\x04 \x01(\x02\"/\n\x05\x41rray\x12&\n\x0borientation\x18\x01 \x03(\x0b\x32\x11.test2.Quaternion')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='test2.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='test2.Quaternion.n1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n2', full_name='test2.Quaternion.n2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n3', full_name='test2.Quaternion.n3', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n4', full_name='test2.Quaternion.n4', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=82,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='test2.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orientation', full_name='test2.Array.orientation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=131,
)

_ARRAY.fields_by_name['orientation'].message_type = _QUATERNION
DESCRIPTOR.message_types_by_name['Quaternion'] = _QUATERNION
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNION,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:test2.Quaternion)
  ))
_sym_db.RegisterMessage(Quaternion)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:test2.Array)
  ))
_sym_db.RegisterMessage(Array)


# @@protoc_insertion_point(module_scope)
